### ISSUE TITLE
Basic things to make this plugin a sweetie

### ISSUE THREAD

**Issue by hilltty** [DenisIndenbom/DiscordAuth#1]
1. the ability to save the player's login after leaving for a certain time (session system)
2. deleting the login confirmation message from the bot after a while
3. mysql database support
4. support for proxy servers (bungeecord / velocity)

after the implementation of all this, you can at least sell the plugin, I wish you good luck in development and I hope the plugin will be updated <3

**Comment by DenisIndenbom** [comment]
Hi,
thanks for the ideas, but I want to explain why I won't implement some ideas:

**(1)** The session system cannot be implemented normally in minecraft because it is assumed that the client stores the session key (as far as I know, the vanilla minecraft client does not store the session key).

**(3)** I do not want and do not see the point of supporting mysql.

**(4)** Sorry, I didn't understand this point, and maybe I'm wrong. Do I think I should write a separate plugin for proxy servers? I don't want to do this.

2 point I will implement, the plugin really needs it.
